### ISSUE TITLE
Allow bucket map to specify bucket&prefix.

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#188]
Can we create a method by which we can define URI path by bucket & object prefix allowing greater flexibility for partitioning access to buckets? I imagine it would look something like this scenario:

In the example below:
- `https://<tea>/pathA/prefix1/object_1.ext` =>  `s3://bucket-name1/prefix1/object_1.ext` would require a user to be in URS group `access_group_a`
- `https://<tea>/pathB/prefix2/object_2.ext` =>`s3://bucket-name1/prefix2/object_2.ext` would require a user to be in URS group `access_group_b`
- `https://<tea>/pathC/some_file.ext` => `s3://bucket-name2/some_file.ext` would require only simple URS auth
- `https://<tea>/pathC/bowse/image.jpg` => `s3://bucket-name2/browse/image.jpg` would be publicly accessible

Questions to be resolvled:
- For Accessing `s3://bucket-name1/prefix1/object_1.ext`, which path makes more sense?
  - `https://<tea>/pathA/prefix1/object_1.ext`
  - `https://<tea>/pathA/object_1.ext`
- Depending on the choice above, 
  - If the first is chosen, what is the value in defining the path like that?! Just to block access to `s3://bucket-name1/hidden.obj`?
  - If the second is chosen, do we need to worry about ambiguity? 

```
MAP:
    pathA: bucket-name1/prefix1
    pathB: bucket-name1/prefix2
    pathC: bucket-name2

PUBLIC_BUCKETS
   bucket-name2/browse: "Browse Imagery
  
PRIVATE_BUCKETS:
   bucket-name1/prefix1:
       - access_group_a
   bucket-name1/prefix2:
       - access_group_b
```

**Comment by benbart** [comment]
a use case:
Say a user has directories in their bucket based on date:
 * bucketname/202001
 * bucketname/202002
 * bucketname/202003
 * bucketname/...
 * bucketname/202008
and they want the latest month to be private, but previous data be public, the bucketmap could be granular enough to have bucketname/202008 as a private bucket.

This of course would require updating the bucketmap periodically, so perhaps there is a better solution

**Comment by bbuechler** [comment]
**IDEA:**

Allow bucket & Prefix in PUBLIC and PRIVATE bucket blocks:

```
MAP:
   general-browse: browse-bucket
   productX: productX
   
PUBLIC_BUCKETS: 
   general-browse: "General browse Imagery"
   productX/browse:  "ProductX Browse Imagery"

PRIVATE_BUCKETS: 
   productX/2020/12: 
    - science_team
```

Where:
- request to `https://<TEA>/productX/<object>` require basic auth
- request to `https://<TEA>/productX/browse/<object>` are public 
- request to `https://<TEA>/productX/2020/12/<object>` require membership in science_team

https://github.com/asfadmin/thin-egress-app/blob/811a7833c0b40f29175b561b4a336115fb01763d/lambda/app.py#L625

That can be achieved by updating `check_public_bucket()` and `check_private_bucket()` to accept an optional `object_uri`, and updating this [basic bucket check](https://github.com/asfadmin/rain-api-core/blob/c992f5ed865e26b53d7dd6b6019257f1fa417d12/rain_api_core/egress_util.py#L160) to be a little more sophisticated:


Below is a few examples/sanity check of how this would work in code:
```python3
def bucket_prefix_match(bucket_check, bucket_map, object=""):
   if bucket_check == bucket_map.split('/')[0] and object.startswith("/".join(bucket_map.split('/')[1:])):
      print("Matched")
   else:
      print("Not Matched")

# No Object Specified Bucket Match
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1')

# Deep match      https://<TEA>/bucket1/prefix1/prefix2/path/object
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1/prefix1/prefix2', \
                    object='prefix1/prefix2/path/object')

# Shallow Match https://<TEA>/bucket1/prefix1/path/object
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1/prefix1', \
                    object='prefix1/path/object')

# Shallow Match, unnecessary trailing slash    https://<TEA>/bucket1/prefix1/path/object
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1/prefix1/', \
                    object='prefix1/path/object')

# Simple match  https://<TEA>/bucket1/object
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1', \
                    object='object')

# Bucket Mismatch https://<TEA>/bucket2/prefix1/path/object
bucket_prefix_match(bucket_check='bucket2', \
                    bucket_map='bucket1/prefix1', \
                    object='prefix1/path/object')

# Bucket Match, Prefix Mismatch    https://<TEA>/bucket1/prefix2/path/object
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1/prefix1', \
                    object='prefix2/path/object')

# No Object Specified Bucket Mis-Match
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket2/prefix1/prefix2')

# No Object Specified Prefix mis-Match
bucket_prefix_match(bucket_check='bucket1', \
                    bucket_map='bucket1/prefix1/prefix2')

```
