### ISSUE TITLE
[rain-api-core] When evaluating object-prefix access constraints, check prefixed blocks first

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#342]
https://github.com/asfadmin/rain-api-core/blob/5cc26ae45c50ef038b30c3a9c0b5fd931a02361e/rain_api_core/egress_util.py#L152-L182

```
MAP:
  nsidc-cumulus-uat-protected: nsidc-cumulus-uat-protected
  nsidc-cumulus-uat-public: nsidc-cumulus-uat-public
PUBLIC_BUCKETS:
  nsidc-cumulus-uat-public: ""
PRIVATE_BUCKETS:
  nsidc-cumulus-uat-protected:
    - Staff UAT
  nsidc-cumulus-uat-protected/ATLAS:
    - ICESat-II Cloud Early Access UAT
    - Staff UAT
```

In the above use case, `check_private_bucket()` matches `nsidc-cumulus-uat-protected` and does not properly evaluate `nsidc-cumulus-uat-protected/ATLAS` causing `ICESat-II Cloud Early Access UAT` to be denied access to `/ATLAS`. 

This can be resolved by running through `PRIVATE_BUCKETS:` blocks that contain `/` BEFORE blocks that DON'T.

Short term fix for above was to re-order `/ATLAS` above the parent bucket, but that is NOT a long-term solution.
