### ISSUE TITLE
[rain-api-core] Allow multi-level object-prefix configurations

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#343]
https://github.com/asfadmin/rain-api-core/blob/5cc26ae45c50ef038b30c3a9c0b5fd931a02361e/rain_api_core/egress_util.py#L152-L182

```
PRIVATE_BUCKETS:
    nsidc-cumulus-uat-protected:
      - ICESat-II Cloud Early Access UAT
      - Staff UAT
    nsidc-cumulus-uat-protected/ATLAS:
      - ICESat-II Cloud Early Access UAT
    nsidc-cumulus-uat-protected/ATLAS/ATL06:
      - Staff UAT
      - ICESat-II Cloud Early Access UAT
    nsidc-cumulus-uat-protected/ATLAS/ATL03:
      - Staff UAT
```

Right now, ONLY the first object prefix is evaluated. We should create a better methodology that allows arbitrary depth prefixes.
